name: finalhemocycle
description: "A new Flutter project."
publish_to: 'none'
environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  shimmer: ^3.0.0
  lottie: ^2.7.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter




  flutter_lints: ^5.0.0


flutter:
  assets:
    - assets/animation/500.json
    - assets/animation/Animation - 1750950749357.json
    - assets/animation/Main Scene.json
    - assets/animation/Main Scene1.json
    - assets/images/avatar.png

  fonts:
    - family: DancingScript
      fonts:
        - asset: assets/fonts/DancingScript-Medium.ttf




  uses-material-design: true

